# Generated by Django 5.2.12 on 2026-06-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_agenttask_plan_agenttask_rationale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Human label for the run.', max_length=300)),
                ('mode', models.CharField(choices=[('review', 'Review'), ('auto', 'Auto')], default='review', max_length=10)),
                ('status', models.CharField(blank=True, default='', help_text='Mirror of derived status; read model recomputes from steps.', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', help_text='Key of the step currently in focus.', max_length=120)),
                ('session_link', models.URLField(blank=True, default='', help_text='Link to the originating Claude/agent session.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('forked_from', models.ForeignKey(blank=True, help_text='The run this was forked from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='agent_runs.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable step key, e.g. the phase/skill slug.', max_length=120)),
                ('ordinal', models.IntegerField(default=0, help_text='Order within the run.')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent_runs.agentrun')),
            ],
            options={
                'ordering': ['run', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, default='', help_text='The decision recorded at the gate.', max_length=120)),
                ('decided_by', models.CharField(blank=True, default='', help_text='Who decided (email).', max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='agent_runs.agentrunstep')),
            ],
            options={
                'ordering': ['step', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='What was being decided.')),
                ('ai_default', models.TextField(blank=True, default='', help_text="The AI's proposed answer.")),
                ('override', models.TextField(blank=True, default='', help_text='The human override, if any.')),
                ('status', models.CharField(choices=[('ai-default', 'AI default'), ('overridden', 'Overridden')], default='ai-default', max_length=20)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('evidence_basis', models.TextField(blank=True, default='', help_text='What the decision was grounded in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agent_runs.agentrunstep')),
            ],
            options={
                'ordering': ['step', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, default='', help_text='Link/ref to the artifact (Drive url, gs://, etc.).', max_length=1000)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(blank=True, help_text='Bytes, if known.', null=True)),
                ('role', models.CharField(blank=True, default='', help_text='Producer skill/tag.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agent_runs.agentrunstep')),
            ],
            options={
                'ordering': ['step', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('judge', 'Judge'), ('qa', 'QA')], max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Per-dimension scores / rubric breakdown.')),
                ('rationale', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='agent_runs.agentrunstep')),
            ],
            options={
                'ordering': ['step', 'kind', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent', '-created_at'], name='agent_runs__agent_i_b84a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['forked_from'], name='agent_runs__forked__86e82b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunstep',
            index=models.Index(fields=['run', 'ordinal'], name='agent_runs__run_id_92583d_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('run', 'key'), name='uniq_run_step_key'),
        ),
        migrations.AddIndex(
            model_name='agentrungate',
            index=models.Index(fields=['step'], name='agent_runs__step_id_c7c96a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrundecision',
            index=models.Index(fields=['step'], name='agent_runs__step_id_30b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['step'], name='agent_runs__step_id_a4f6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunverdict',
            index=models.Index(fields=['step', 'kind'], name='agent_runs__step_id_7c143d_idx'),
        ),
    ]
