# Generated by Django 5.2.12 on 2026-05-31 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(db_index=True, max_length=200)),
                ('args_summary', models.CharField(blank=True, default='', max_length=500)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mcp_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mcp_audit_l_user_id_7874dd_idx'), models.Index(fields=['tool', '-created_at'], name='mcp_audit_l_tool_ecac65_idx')],
            },
        ),
    ]
