# Generated by Django 5.2.12 on 2026-04-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_skills_projectguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['project', 'skill_name', '-started_at'], name='projects_pr_project_80ed1a_idx')],
            },
        ),
    ]
