# Generated by Django 5.2.12 on 2026-04-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectGuide',
        ),
    ]
