# Generated by Django 5.2.12 on 2026-07-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_drop_skills_evals_collections_tables'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The tenant that owns this project. Nullable for migration safety; the API always assigns one (default workspace when unspecified).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='workspaces.workspace'),
        ),
    ]
