# Generated by Django 5.2.12 on 2026-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_sessions', '0002_sessionarc_arcsharetoken_sessionarcitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
