# Generated by Django 5.2.12 on 2026-06-17 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('persona', models.TextField(blank=True, default='', help_text='Who the agent is / its remit.')),
                ('email', models.EmailField(blank=True, default='', help_text="The agent's own mailbox, if any.", max_length=254)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The human who operates the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', help_text='Link to the SKILL.md.', max_length=500)),
                ('improvement_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='agents.agent')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'name'), name='uniq_agent_skill')],
            },
        ),
        migrations.CreateModel(
            name='AgentSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('doc_url', models.URLField(help_text='The Google Doc holding the full sync.', max_length=500)),
                ('self_grades', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='agents.agent')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['agent', '-period_end'], name='agents_agen_agent_i_02d177_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, default='', help_text='doc / form / story / …', max_length=40)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_products', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'url'), name='uniq_agent_workproduct_url')],
            },
        ),
    ]
