# Generated by Django 5.2.12 on 2026-06-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(help_text='Stable id from the source sheet.', max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(blank=True, default='', help_text='high / medium / low', max_length=20)),
                ('owner', models.CharField(blank=True, default='', help_text='Owner / requester.', max_length=120)),
                ('due', models.DateField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0, help_text='Order within a status column.')),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.agent')),
            ],
            options={
                'ordering': ['status', 'position', 'id'],
                'indexes': [models.Index(fields=['agent', 'status'], name='agents_agen_agent_i_26e092_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'ext_id'), name='uniq_agent_task_extid')],
            },
        ),
    ]
