# Generated by Django 5.2.12 on 2026-06-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agenttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='priority',
        ),
        migrations.AddField(
            model_name='agenttask',
            name='assigned',
            field=models.CharField(blank=True, default='', help_text='Who the next action waits on — the agent or a person.', max_length=120),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='confidence',
            field=models.CharField(blank=True, default='', help_text='high / low — how sure the agent is about a suggestion.', max_length=10),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='next_action',
            field=models.CharField(blank=True, default='', help_text='The single concrete next step (verb-first).', max_length=300),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='owner',
            field=models.CharField(blank=True, default='', help_text='Human stakeholder who owns the outcome — never the agent.', max_length=120),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('in_progress', 'In progress'), ('done', 'Done'), ('declined', 'Declined')], default='suggested', max_length=20),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='title',
            field=models.CharField(help_text='The outcome.', max_length=300),
        ),
    ]
