# Generated by Django 5.2.12 on 2026-06-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agenttask_priority_agenttask_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='plan',
            field=models.TextField(blank=True, default='', help_text='Proposed first steps.'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Why the agent suggested this / why now.'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Originating thread / report / link.', max_length=500),
        ),
        migrations.CreateModel(
            name='AgentTaskCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accept', 'accept'), ('decline', 'decline'), ('dispatch', 'dispatch'), ('reassign', 'reassign'), ('edit', 'edit'), ('comment', 'comment'), ('done', 'done')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='reason / assignee / next_action / note …')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', help_text='Who clicked it (email).', max_length=200)),
                ('result_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.agent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='agents.agenttask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='agents_agen_agent_i_6970c7_idx')],
            },
        ),
    ]
