# Generated by Django 5.2.12 on 2026-06-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runs', '0001_initial'),
        ('agents', '0004_agenttask_plan_agenttask_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='run',
            field=models.ForeignKey(blank=True, help_text='The run this task executes, if the task is run-backed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='agent_runs.agentrun'),
        ),
    ]
