# Generated by Django 5.2.12 on 2026-06-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agenttask_run'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The tenant that owns this agent. Nullable for migration safety; the API always assigns one (default workspace when unspecified).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='workspaces.workspace'),
        ),
    ]
