# Generated by Django 5.2.12 on 2026-07-02 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_backfill_default_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_session_id', models.CharField(help_text='Claude Code session id — the dedup key.', max_length=100)),
                ('title', models.CharField(help_text='What the turn did, in one line.', max_length=300)),
                ('summary', models.TextField(blank=True, default='', help_text='The close-out summary.')),
                ('task_ext_ids', models.JSONField(blank=True, default=list)),
                ('work_product_urls', models.JSONField(blank=True, default=list)),
                ('session_slug', models.CharField(blank=True, default='', help_text='Uploaded Session.slug, if any.', max_length=64)),
                ('share_token', models.CharField(blank=True, default='', help_text='Public /share/<token>, if shared.', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='agents_agen_agent_i_31eb4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'cli_session_id'), name='uniq_agent_turn_session')],
            },
        ),
    ]
