# Generated by Django 5.2.12 on 2026-07-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='args_hint',
            field=models.CharField(blank=True, default='', help_text='What the command takes, e.g. "topic (optional)". Renders as the input placeholder.', max_length=120),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='launchable',
            field=models.BooleanField(default=False, help_text='Offer this skill as a command on the phone composer.'),
        ),
    ]
