# Generated by Django 5.2.12 on 2026-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentskill_args_hint_agentskill_launchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='review',
            field=models.TextField(blank=True, default='', help_text='One-line self-review captured when the task was completed.'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='score',
            field=models.CharField(blank=True, default='', help_text='Self-grade at completion — e.g. A-, B+, 4/5.', max_length=8),
        ),
    ]
