# Generated by Django 5.2.12 on 2026-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agenttask_review_agenttask_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='repo_ref',
            field=models.CharField(blank=True, default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='repo_url',
            field=models.CharField(blank=True, default='', help_text="Agent's git repo (holds runtime.yaml).", max_length=300),
        ),
        migrations.AddField(
            model_name='agent',
            name='runtime_engine',
            field=models.CharField(choices=[('emdash', 'emdash'), ('cloud_p', 'cloud-p (claude -p)'), ('any', 'any')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='runtime_secrets',
            field=models.JSONField(blank=True, default=list, help_text='Secret-reference NAMES this agent needs (never values), e.g. ["canopy-pat","echo-gog"]. The reconciler resolves each from the env store.'),
        ),
    ]
