# Generated by Django 5.2.12 on 2026-07-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_repo_ref_agent_repo_url_agent_runtime_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='runner_preference',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
