# Generated by Django 5.2.12 on 2026-05-26 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('html', 'HTML'), ('video', 'Video')], max_length=10)),
                ('project_slug', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (dimagi only)'), ('link', 'Link (anyone with token)')], default='private', max_length=10)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('drive_file_id', models.CharField(max_length=128)),
                ('drive_folder_id', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walkthroughs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_slug', '-created_at'], name='walkthrough_project_d7b244_idx'), models.Index(fields=['owner', '-created_at'], name='walkthrough_owner_i_1f4193_idx')],
            },
        ),
    ]
