# Generated by Django 5.2.12 on 2026-06-02 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0002_walkthrough_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='feature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='walkthrough',
            index=models.Index(fields=['run_id', '-created_at'], name='walkthrough_run_id_b37357_idx'),
        ),
    ]
