# Generated by Django 5.2.12 on 2026-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0003_walkthrough_feature_walkthrough_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='narrative_review_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
