# Generated by Django 5.2.12 on 2026-07-01 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughs', '0005_rename_feature_narrative_slug'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The tenant that owns this walkthrough. Nullable for migration safety; the API always assigns one (default workspace when unspecified).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='walkthroughs', to='workspaces.workspace'),
        ),
    ]
