# Generated by Django 5.2.12 on 2026-06-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_drop_project_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('links', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Null = cross-project roll-up for the period.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareouts', to='projects.project')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['-period_end', '-period_start'], name='shareouts_s_period__92ffdd_idx')],
            },
        ),
    ]
