# Generated by Django 5.2.12 on 2026-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareout',
            name='all_prs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
