# Generated by Django 5.2.12 on 2026-06-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareouts', '0002_shareout_all_prs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareout',
            name='period_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shareout',
            name='period_start',
            field=models.DateTimeField(),
        ),
    ]
