# Generated by Django 5.2.12 on 2026-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareouts', '0005_backfill_default_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareout',
            name='produced_by_agent',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
