# Generated by Django 5.2.12 on 2026-03-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('analyzing', 'Analyzing Sources'), ('proposed', 'Approach Proposed'), ('editing', 'User Editing'), ('testing', 'Running Eval'), ('published', 'Published')], default='created', max_length=20)),
                ('proposed_approach', models.JSONField(blank=True, default=dict)),
                ('proposed_eval_cases', models.JSONField(blank=True, default=list)),
                ('skill_draft', models.JSONField(blank=True, default=dict)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_sessions', to='collections.collection')),
            ],
        ),
    ]
