# Generated by Django 5.2.12 on 2026-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(default='hal-architect', max_length=100)),
                ('agent', models.CharField(default='hal', max_length=100)),
                ('skill', models.CharField(default='architect', max_length=100)),
                ('initiative', models.CharField(default='', max_length=200)),
                ('ledger', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.CharField(default='', max_length=40)),
                ('disposition', models.CharField(default='route', max_length=20)),
                ('confidence', models.CharField(default='medium', max_length=20)),
                ('mandate', models.TextField(blank=True, default='')),
                ('done_when', models.TextField(blank=True, default='')),
                ('intent', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('corpus', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('repo', 'number'), name='uniq_origin_issue_repo_number')],
            },
        ),
    ]
