# Generated by Django 5.2.12 on 2026-07-17 04:23

import django.db.models.deletion
from django.db import migrations, models


def _backfill_workspace_from_agent(apps, schema_editor):
    """An origin record derives its tenant from the agent that authored it — set
    each existing row's workspace to its `agent` slug's Agent.workspace. Rows whose
    agent slug doesn't resolve stay null (visible to any authenticated caller until
    re-upserted)."""
    OriginIssue = apps.get_model("issues", "OriginIssue")
    Agent = apps.get_model("agents", "Agent")
    agent_ws = dict(Agent.objects.values_list("slug", "workspace_id"))
    for issue in OriginIssue.objects.filter(workspace__isnull=True):
        ws_id = agent_ws.get(issue.agent)
        if ws_id:
            issue.workspace_id = ws_id
            issue.save(update_fields=["workspace"])


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('workspaces', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originissue',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_issues', to='workspaces.workspace'),
        ),
        migrations.RunPython(_backfill_workspace_from_agent, migrations.RunPython.noop),
    ]
