# Generated by Django 5.2.12 on 2026-07-23 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agent_runner_preference'),
        ('canopy_sessions', '0002_draft_sessionparticipant'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('agent__isnull', True), ('project', ''), _connector='OR'), name='chat_session_not_agent_and_project'),
        ),
    ]
