# Generated by Django 5.2.12 on 2026-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0005_runnerbinding'),
        ('harness', '0021_runnerbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='agent_task_ext_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='runnerbinding',
            name='host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='runnerbinding',
            name='thread_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='runnerbinding',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='runnerbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('runner__isnull', False), models.Q(('session_key', ''), _negated=True)), fields=('runner', 'session_key'), name='one_binding_per_runner_session_key'),
        ),
    ]
