# Generated by Django 5.2.12 on 2026-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0006_runnerbinding_reuse_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='stream_desired',
            field=models.BooleanField(default=False),
        ),
    ]
