# Generated by Django 5.2.12 on 2026-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0007_runnerbinding_stream_desired'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='backfill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
