# Generated by Django 5.2.12 on 2026-07-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentturn'),
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWaitingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_snapshot', to='agents.agent')),
            ],
        ),
    ]
