# Generated by Django 5.2.12 on 2026-07-13 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0007_backfill_default_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('emdash', 'Emdash'), ('cloud', 'Cloud'), ('remote', 'Remote')], max_length=10)),
                ('capabilities', models.JSONField(default=dict, help_text='e.g. {"agents": ["echo"]}')),
                ('status', models.CharField(choices=[('online', 'Online'), ('stale', 'Stale'), ('disconnected', 'Disconnected'), ('degraded', 'Degraded'), ('retired', 'Retired')], default='disconnected', max_length=12)),
                ('status_note', models.CharField(blank=True, default='', max_length=255)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('board', 'Board'), ('api', 'API'), ('slack', 'Slack'), ('cron', 'Cron'), ('manual', 'Manual')], max_length=10)),
                ('origin_ref', models.JSONField(blank=True, default=dict)),
                ('prompt', models.TextField(blank=True, default='')),
                ('routing', models.CharField(choices=[('prefer_local', 'Prefer local'), ('local_only', 'Local only'), ('any', 'Any')], default='prefer_local', max_length=15)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('needs_human', 'Needs human'), ('done', 'Done'), ('failed', 'Failed'), ('lost', 'Lost')], default='queued', max_length=12)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('result_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harness_turns', to='agents.agent')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='harness.runner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='harness.turn')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='runner',
            index=models.Index(fields=['kind', 'status'], name='harness_run_kind_e99424_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['status', 'created_at'], name='harness_tur_status_14f50c_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['agent', 'status'], name='harness_tur_agent_i_8bec7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['claimed', 'running', 'needs_human'])), fields=('agent',), name='one_executing_turn_per_agent'),
        ),
        migrations.AddConstraint(
            model_name='turnevent',
            constraint=models.UniqueConstraint(fields=('turn', 'seq'), name='turnevent_seq_unique_per_turn'),
        ),
    ]
