# Generated by Django 5.2.12 on 2026-07-14 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentturn'),
        ('harness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='SessionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_key', models.CharField(help_text='Gmail thread_id or a topic key', max_length=255)),
                ('agent_task_ext_id', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Rolling context for rehydration')),
                ('live_host', models.CharField(blank=True, default='', max_length=200)),
                ('live_emdash_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('live_session_id', models.CharField(blank=True, default='', max_length=64)),
                ('live_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='agents.agent')),
                ('live_runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_links', to='harness.runner')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['agent', 'thread_key'], name='harness_ses_agent_i_bd18a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'thread_key'), name='sessionlink_unique_per_agent_thread')],
            },
        ),
    ]
