# Generated by Django 5.2.12 on 2026-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0002_runner_host_sessionlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='origin',
            field=models.CharField(choices=[('board', 'Board'), ('api', 'API'), ('slack', 'Slack'), ('cron', 'Cron'), ('manual', 'Manual'), ('email', 'Email')], max_length=10),
        ),
    ]
