# Generated by Django 5.2.12 on 2026-07-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0003_alter_turn_origin'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text="The tenant that owns this runner. Nullable for migration safety; the API assigns one at pairing (the pairer's default workspace when unspecified). Mirrors Agent.workspace.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runners', to='workspaces.workspace'),
        ),
    ]
