# Generated by Django 5.2.12 on 2026-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0005_backfill_runner_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('needs_human', 'Needs human'), ('done', 'Done'), ('failed', 'Failed'), ('lost', 'Lost'), ('missed', 'Missed')], default='queued', max_length=12),
        ),
    ]
