# Generated by Django 5.2.12 on 2026-07-15 17:46

import apps.harness.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentturn'),
        ('harness', '0006_turn_missed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Weekly manager report"', max_length=200)),
                ('prompt', models.TextField(help_text='What the turn is seeded with, e.g. /echo:manager-report')),
                ('cron', models.CharField(help_text="5-field cron expression, e.g. '0 9 * * 5'", max_length=120)),
                ('timezone', models.CharField(default='UTC', help_text='IANA tz, e.g. America/New_York', max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='Pause without deleting.')),
                ('routing', models.CharField(choices=[('prefer_local', 'Prefer local'), ('local_only', 'Local only'), ('any', 'Any')], default='prefer_local', max_length=15)),
                ('grace_minutes', models.PositiveIntegerField(default=120, help_text='How long an unattended fired turn may hold the agent before it is released as MISSED. Guards one_executing_turn_per_agent: an abandoned session would otherwise wedge the agent indefinitely.')),
                ('notify', models.JSONField(blank=True, default=apps.harness.models._default_notify, help_text='Channel ids resolved through the notify registry, e.g. ["inbox"].')),
                ('last_slot', models.DateTimeField(blank=True, help_text='Newest slot fired. The supersede + no-backfill anchor.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agent')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['agent', 'enabled'], name='harness_age_agent_i_ea5cd8_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'name'), name='uniq_agent_schedule_name')],
            },
        ),
    ]
