# Generated by Django 5.2.12 on 2026-07-15 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentturn'),
        ('harness', '0007_agentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('board', 'Board'), ('api', 'API'), ('slack', 'Slack'), ('cron', 'Cron'), ('manual', 'Manual'), ('email', 'Email')], max_length=10)),
                ('origin_ref', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('review', 'Review'), ('question', 'Question')], default='review', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('open', 'Open'), ('decided', 'Decided'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('decision', models.CharField(blank=True, choices=[('implement', 'Implement'), ('skip', 'Skip'), ('defer', 'Defer')], default='', max_length=10)),
                ('comment', models.TextField(blank=True, default='', help_text="kind=review: the reviewer's note (optional). kind=question: the answer (required to decide).")),
                ('decided_by', models.CharField(blank=True, default='', max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch', models.JSONField(blank=True, default=list, help_text='[TurnSpec] — deferred Turn enqueues fired on implement. e.g. [{"target_agent": "hal", "prompt": "/hal:turn", "origin": "email"}]')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('batch_key', models.CharField(blank=True, db_index=True, default='', help_text='Groups items reviewed in one sitting (e.g. a fleet audit).', max_length=120)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text="Whose queue this belongs to — the agent ASKING, not the dispatch target. Tenancy rides this FK, as Turn's does.", on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agents.agent')),
                ('raised_by', models.ForeignKey(blank=True, help_text='The turn that produced this item. Null for items raised outside a turn (an email poll, a manual post).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_items', to='harness.turn')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='turn',
            name='raised_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_turns', to='harness.item'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['agent', 'state'], name='harness_ite_agent_i_99d621_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['state', 'created_at'], name='harness_ite_state_01fe53_idx'),
        ),
    ]
