# Generated by Django 5.2.12 on 2026-07-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentskill_args_hint_agentskill_launchable'),
        ('harness', '0008_item'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='project',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turn',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Set only for project turns, which have no agent to derive tenancy from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_turns', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harness_turns', to='agents.agent'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('project', '')), models.Q(('agent__isnull', True), models.Q(('project', ''), _negated=True)), _connector='OR'), name='turn_targets_agent_xor_project'),
        ),
    ]
