# Generated by Django 5.2.12 on 2026-07-16 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentskill_args_hint_agentskill_launchable'),
        ('harness', '0009_turn_project_turn_workspace_alter_turn_agent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionlink',
            name='sessionlink_unique_per_agent_thread',
        ),
        migrations.AddField(
            model_name='sessionlink',
            name='project',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionlink',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='sessionlink',
            index=models.Index(fields=['project', 'thread_key'], name='harness_ses_project_d0fef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('agent', 'thread_key'), name='sessionlink_unique_per_agent_thread'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', True)), fields=('project', 'thread_key'), name='sessionlink_unique_per_project_thread'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('project', '')), models.Q(('agent__isnull', True), models.Q(('project', ''), _negated=True)), _connector='OR'), name='sessionlink_targets_agent_xor_project'),
        ),
    ]
