# Generated by Django 5.2.12 on 2026-07-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentskill_args_hint_agentskill_launchable'),
        ('harness', '0010_remove_sessionlink_sessionlink_unique_per_agent_thread_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionlink',
            name='sessionlink_unique_per_project_thread',
        ),
        migrations.RemoveConstraint(
            model_name='sessionlink',
            name='sessionlink_targets_agent_xor_project',
        ),
        migrations.AddField(
            model_name='sessionlink',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_session_links', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', True)), fields=('project', 'workspace', 'thread_key'), name='sessionlink_unique_per_project_thread'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('project', ''), ('workspace__isnull', True)), models.Q(('agent__isnull', True), models.Q(('project', ''), _negated=True), ('workspace__isnull', False)), _connector='OR'), name='sessionlink_targets_agent_xor_project'),
        ),
    ]
