# Generated by Django 5.2.12 on 2026-07-16 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0011_remove_sessionlink_sessionlink_unique_per_project_thread_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmdashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emdash_task', models.CharField(help_text='The emdash task NAME — what open_and_send targets.', max_length=200)),
                ('project', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('last_interacted_at', models.DateTimeField(blank=True, null=True)),
                ('recent_messages', models.JSONField(blank=True, default=list)),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emdash_sessions', to='harness.runner')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emdash_sessions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_interacted_at'],
                'constraints': [models.UniqueConstraint(fields=('runner', 'emdash_task'), name='emdashsession_unique_per_runner_task')],
            },
        ),
    ]
