# Generated by Django 5.2.12 on 2026-07-17 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agenttask_review_agenttask_score'),
        ('canopy_sessions', '0001_initial'),
        ('harness', '0012_emdashsession'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turn',
            name='turn_targets_agent_xor_project',
        ),
        migrations.AddField(
            model_name='turn',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='canopy_sessions.session'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['claimed', 'running', 'needs_human'])), fields=('chat_session',), name='one_executing_turn_per_session'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('chat_session__isnull', True), ('project', '')), models.Q(('agent__isnull', True), ('chat_session__isnull', True), models.Q(('project', ''), _negated=True)), models.Q(('agent__isnull', True), ('chat_session__isnull', False), ('project', '')), _connector='OR'), name='turn_targets_agent_xor_project_xor_session'),
        ),
    ]
