# Generated by Django 5.2.12 on 2026-07-17 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0013_turn_chat_session_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
