# Generated by Django 5.2.12 on 2026-07-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0014_agentschedule_created_by_agentschedule_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='enqueued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns_enqueued', to=settings.AUTH_USER_MODEL),
        ),
    ]
