# Generated by Django 5.2.12 on 2026-07-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_decided_by_user(apps, schema_editor):
    """Match each already-decided item's `decided_by` email to a User, best-effort.
    Items decided via the API always carried a real user's email, so most resolve;
    any that don't keep the string (decided_by) as the display fallback."""
    Item = apps.get_model("harness", "Item")
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".", 1)[0], settings.AUTH_USER_MODEL.split(".", 1)[1])
    by_email = {u.email: u.pk for u in User.objects.exclude(email="") if u.email}
    for item in Item.objects.filter(decided_by_user__isnull=True).exclude(decided_by=""):
        uid = by_email.get(item.decided_by)
        if uid:
            item.decided_by_user_id = uid
            item.save(update_fields=["decided_by_user"])


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0015_turn_enqueued_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decided_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_backfill_decided_by_user, migrations.RunPython.noop),
    ]
