# Generated by Django 5.2.12 on 2026-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0016_item_decided_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='ready_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
