# Generated by Django 5.2.12 on 2026-07-21 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0017_runner_ready_runner_ready_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claude_token_enc', models.TextField(blank=True, default='')),
                ('github_token_enc', models.TextField(blank=True, default='')),
                ('op_sa_token_enc', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='harness.runner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
