# Generated by Django 5.2.12 on 2026-07-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0017_runner_ready_runner_ready_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='code_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
