# Generated by Django 5.2.12 on 2026-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0019_runnercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='engine',
            field=models.CharField(choices=[('emdash', 'emdash')], default='emdash', help_text='The agent engine this runner drives (not assumed to be emdash).', max_length=32),
        ),
        migrations.AddField(
            model_name='runner',
            name='location',
            field=models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud')], default='local', help_text='Where the runner runs. Drives the session persistence tier.', max_length=16),
        ),
    ]
