# Generated by Django 5.2.12 on 2026-07-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0020_runner_location_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmdashSession',
        ),
    ]
