# Generated by Django 5.2.12 on 2026-07-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0021_runnerbinding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionLink',
        ),
    ]
