# Generated by Django 5.2.12 on 2026-06-16 14:54

import apps.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=apps.sessions.models.generate_slug, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('project_slug', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (dimagi only)'), ('link', 'Link (anyone with token)')], default='link', max_length=10)),
                ('cli_session_id', models.CharField(blank=True, default='', max_length=200)),
                ('redaction_count', models.IntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, default='', max_length=500)),
                ('raw_bytes', models.BigIntegerField(default=0)),
                ('line_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.IntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool_use', 'Tool use'), ('tool_result', 'Tool result')], max_length=16)),
                ('content', models.JSONField()),
                ('plaintext', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared_sessions.session')),
            ],
            options={
                'db_table': 'shared_session_messages',
                'ordering': ['session_id', 'turn_index'],
            },
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.sessions.models.generate_share_token, max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_session_share_tokens', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='shared_sessions.session')),
            ],
            options={
                'db_table': 'shared_session_share_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner', '-created_at'], name='shared_sess_owner_i_814be4_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['project_slug', '-created_at'], name='shared_sess_project_b95f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='unique_shared_session_turn'),
        ),
    ]
