# Generated by Django 5.2.12 on 2026-06-22 14:37

import apps.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=apps.sessions.models.generate_slug, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('project_slug', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (dimagi only)'), ('link', 'Link (anyone with token)')], default='link', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_session_arcs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_session_arcs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArcShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.sessions.models.generate_share_token, max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_session_arc_share_tokens', to=settings.AUTH_USER_MODEL)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='shared_sessions.sessionarc')),
            ],
            options={
                'db_table': 'shared_session_arc_share_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionArcItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('heading', models.CharField(blank=True, default='', max_length=500)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shared_sessions.sessionarc')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc_memberships', to='shared_sessions.session')),
            ],
            options={
                'db_table': 'shared_session_arc_items',
                'ordering': ['arc_id', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionarc',
            index=models.Index(fields=['owner', '-created_at'], name='shared_sess_owner_i_ee33ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionarc',
            index=models.Index(fields=['project_slug', '-created_at'], name='shared_sess_project_f73306_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionarcitem',
            constraint=models.UniqueConstraint(fields=('arc', 'position'), name='unique_arc_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionarcitem',
            constraint=models.UniqueConstraint(fields=('arc', 'session'), name='unique_arc_session'),
        ),
    ]
