# Generated by Django 5.2.12 on 2026-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_sessions', '0003_session_ended_at_session_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
