# Generated by Django 5.2.12 on 2026-05-28 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(db_index=True, max_length=255)),
                ('gate', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=16)),
                ('request_json', models.JSONField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (dimagi only)'), ('link', 'Link (anyone with token)')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run_id', '-created_at'], name='reviews_rev_run_id_d64bfc_idx'), models.Index(fields=['status', '-created_at'], name='reviews_rev_status_71287a_idx')],
            },
        ),
    ]
