# Generated by Django 5.2.12 on 2026-06-03 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='feature',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='version',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['feature', 'version'], name='reviews_rev_feature_277fdd_idx'),
        ),
    ]
