# Generated by Django 5.2.12 on 2026-06-05 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_feature_narrative_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewrequest',
            name='reviews_rev_feature_277fdd_idx',
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['narrative_slug', 'version'], name='reviews_rev_narrati_6c958a_idx'),
        ),
    ]
