# Generated by Django 5.2.12 on 2026-07-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_reviewrequest_reviews_rev_feature_277fdd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (dimagi only)'), ('link', 'Public (anyone with the link)')], default='private', max_length=10),
        ),
    ]
