# Generated by Django 5.2.12 on 2026-07-01 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewrequest_visibility'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The tenant that owns this review. Nullable for migration safety; the API always assigns one (default workspace when unspecified). A review with a narrative_slug is a DDD narrative version, but it is still its own tenant root via this FK.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='workspaces.workspace'),
        ),
    ]
