# Generated by Django 5.2.12 on 2026-07-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_backfill_default_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='suggestions_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
