# Generated by Django 5.2.12 on 2026-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_session_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='origin',
            field=models.CharField(choices=[('web', 'Web'), ('runner', 'Runner')], default='web', max_length=10),
        ),
    ]
