# Generated by Django 5.2.12 on 2026-07-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_session_origin'),
        ('harness', '0021_runnerbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('tail', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('last_interacted_at', models.DateTimeField(blank=True, null=True)),
                ('live_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_bindings', to='harness.runner')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner_binding', to='chat.session')),
            ],
            options={
                'ordering': ['-last_interacted_at'],
            },
        ),
    ]
